import { RatioType } from './graphql';

export const origworld = {
  name: 'A Nice World 2',
  logo: 'icones/ecolo.jpg',
  money: 0,
  score: 0,
  totalangels: 0,
  activeangels: 0,
  angelbonus: 2,
  lastupdate: 0,
  products: [
    {
      id: 1,
      name: 'Velociraptor Training',
      logo: 'icones/velociraptor.jpg',
      cout: 5,
      croissance: 1.07,
      revenu: 2,
      vitesse: 1000,
      quantite: 1,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Speedy Raptors!',
          logo: 'icones/velociraptor.jpg',
          seuil: 20,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Ultimate Pack Hunting!',
          logo: 'icones/velociraptor.jpg',
          seuil: 75,
          idcible: 1,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 2,
      name: 'Triceratops Farm',
      logo: 'icones/triceratops.jpg',
      cout: 50,
      croissance: 1.15,
      revenu: 80,
      vitesse: 3000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Strong Horns!',
          logo: 'icones/triceratops.jpg',
          seuil: 20,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
        {
          name: 'Tricera Rampage!',
          logo: 'icones/triceratops.jpg',
          seuil: 75,
          idcible: 2,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 3,
      name: 'Pterodactyl Aviary',
      logo: 'icones/pterodactyl.jpg',
      cout: 250,
      croissance: 1.12,
      revenu: 300,
      vitesse: 5000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Faster Wings!',
          logo: 'icones/pterodactyl.jpg',
          seuil: 20,
          idcible: 3,
          ratio: 2,
          typeratio: RatioType.vitesse,
          unlocked: false,
        },
      ],
    },
    {
      id: 4,
      name: 'Tyrannosaurus Rex Pen',
      logo: 'icones/t_rex.jpg',
      cout: 1000,
      croissance: 1.10,
      revenu: 1000,
      vitesse: 10000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
      paliers: [
        {
          name: 'Bigger Bite!',
          logo: 'icones/t_rex.jpg',
          seuil: 20,
          idcible: 4,
          ratio: 2,
          typeratio: RatioType.gain,
          unlocked: false,
        },
      ],
    },
    {
      id: 5,
      name: 'Brachiosaurus Sanctuary',
      logo: 'icones/brachiosaurus.jpg',
      cout: 5000,
      croissance: 1.09,
      revenu: 5000,
      vitesse: 20000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
    },
    {
      id: 6,
      name: 'Mosasaurus Lagoon',
      logo: 'icones/mosasaurus.jpg',
      cout: 20000,
      croissance: 1.08,
      revenu: 20000,
      vitesse: 60000,
      quantite: 0,
      timeleft: 0,
      managerUnlocked: false,
    },
  ],
  allunlocks: [
    {
      name: 'Jurassic Domination',
      logo: 'icones/all.jpg',
      seuil: 30,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  upgrades: [
    {
      name: 'Raptor Speed Boost',
      logo: 'icones/velociraptor.jpg',
      seuil: 1000,
      idcible: 1,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'T-Rex Raw Power',
      logo: 'icones/t_rex.jpg',
      seuil: 50000,
      idcible: 4,
      ratio: 3,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  angelupgrades: [
    {
      name: 'Angelic Dino Growth',
      logo: 'icones/angel.png',
      seuil: 50,
      idcible: 0,
      ratio: 2,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
  managers: [
    {
      name: 'Dr. Alan Grant',
      logo: 'icones/alan_grant.jpg',
      seuil: 5000,
      idcible: 1,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'John Hammond',
      logo: 'icones/john_hammond.jpg',
      seuil: 15000,
      idcible: 2,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Owen Grady',
      logo: 'icones/owen_grady.jpg',
      seuil: 30000,
      idcible: 3,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Dr. Ellie Sattler',
      logo: 'icones/ellie_sattler.jpg',
      seuil: 60000,
      idcible: 4,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Claire Dearing',
      logo: 'icones/claire_dearing.jpg',
      seuil: 120000,
      idcible: 5,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
    {
      name: 'Dr. Ian Malcolm',
      logo: 'icones/ian_malcolm.jpg',
      seuil: 250000,
      idcible: 6,
      ratio: 0,
      typeratio: RatioType.gain,
      unlocked: false,
    },
  ],
};